import {
  HOME_LABEL,
  HOME_PATH,
  SERVICES_LABEL,
  SERVICES_PATH,
  CONTACT_US_LABEL,
  CONTACT_US_PATH,
  MISSIOM_LABEL,
  MISSIOM_PATH,
  ABOUT_LABEL,
  ABOUT_PATH,
} from './strings'

export const LANDING_PAGE_ROUTES = [
  { label: HOME_LABEL, path: HOME_PATH },
  { label: SERVICES_LABEL, path: SERVICES_PATH },
  { label: CONTACT_US_LABEL, path: CONTACT_US_PATH },
  { label: MISSIOM_LABEL, path: MISSIOM_PATH },
  { label: ABOUT_LABEL, path: ABOUT_PATH },
]
